# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/TanTai/python-app/UI/item.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MovieItemWidget(object):
    def setupUi(self, MovieItemWidget):
        MovieItemWidget.setObjectName("MovieItemWidget")
        MovieItemWidget.resize(380, 250)
        self.verticalLayout = QtWidgets.QVBoxLayout(MovieItemWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bannerLabel = QtWidgets.QLabel(parent=MovieItemWidget)
        self.bannerLabel.setMinimumSize(QtCore.QSize(0, 150))
        self.bannerLabel.setMaximumSize(QtCore.QSize(16777215, 150))
        self.bannerLabel.setScaledContents(True)
        self.bannerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.bannerLabel.setObjectName("bannerLabel")
        self.verticalLayout.addWidget(self.bannerLabel)
        self.titleLabel = QtWidgets.QLabel(parent=MovieItemWidget)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.btn_favorite = QtWidgets.QPushButton(parent=MovieItemWidget)
        self.btn_favorite.setObjectName("btn_favorite")
        self.buttonLayout.addWidget(self.btn_favorite)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.playButton = QtWidgets.QPushButton(parent=MovieItemWidget)
        self.playButton.setObjectName("playButton")
        self.buttonLayout.addWidget(self.playButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.infoButton = QtWidgets.QPushButton(parent=MovieItemWidget)
        self.infoButton.setObjectName("infoButton")
        self.buttonLayout.addWidget(self.infoButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(MovieItemWidget)
        QtCore.QMetaObject.connectSlotsByName(MovieItemWidget)

    def retranslateUi(self, MovieItemWidget):
        _translate = QtCore.QCoreApplication.translate
        MovieItemWidget.setWindowTitle(_translate("MovieItemWidget", "Movie Item"))
        self.titleLabel.setText(_translate("MovieItemWidget", "Movie Title"))
        self.btn_favorite.setText(_translate("MovieItemWidget", "Favorite"))
        self.playButton.setText(_translate("MovieItemWidget", "Play"))
        self.infoButton.setText(_translate("MovieItemWidget", "Info"))
