# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/TanTai/python-app/UI/Login.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1192, 670)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 240, 81, 20))
        self.label.setObjectName("label")
        self.txt_email = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_email.setEnabled(True)
        self.txt_email.setGeometry(QtCore.QRect(450, 240, 251, 28))
        self.txt_email.setObjectName("txt_email")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 290, 81, 20))
        self.label_2.setObjectName("label_2")
        self.txt_email_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_email_2.setGeometry(QtCore.QRect(450, 290, 251, 28))
        self.txt_email_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.txt_email_2.setObjectName("txt_email_2")
        self.login_bt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.login_bt.setGeometry(QtCore.QRect(520, 370, 83, 29))
        self.login_bt.setObjectName("login_bt")
        self.rgt_bt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rgt_bt.setGeometry(QtCore.QRect(520, 440, 83, 29))
        self.rgt_bt.setObjectName("rgt_bt")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 440, 161, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(840, 110, 351, 521))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/TanTai/python-app/UI/the_netflix_login_background__canada__2024___by_logofeveryt_dh0w8qv-pre.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Username"))
        self.txt_email.setText(_translate("MainWindow", "Enter username"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.txt_email_2.setText(_translate("MainWindow", "Enter password"))
        self.login_bt.setText(_translate("MainWindow", "Login"))
        self.rgt_bt.setText(_translate("MainWindow", "Register"))
        self.label_3.setText(_translate("MainWindow", "Don\'t have an account?"))
