# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/TanTai/python-app/UI/Register.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1028, 625)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setStyleSheet("background-image: url(img/background.jpg);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 190, 71, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 260, 63, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(390, 330, 63, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 400, 121, 20))
        self.label_4.setObjectName("label_4")
        self.txt_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_name.setGeometry(QtCore.QRect(390, 220, 231, 31))
        self.txt_name.setStyleSheet("border: 2px solid #e67e22;\n"
"border-radius: 7px;\n"
"padding: 5px;")
        self.txt_name.setObjectName("txt_name")
        self.txt_email = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_email.setGeometry(QtCore.QRect(390, 290, 231, 31))
        self.txt_email.setStyleSheet("border: 2px solid #e67e22;\n"
"border-radius: 7px;\n"
"padding: 5px;")
        self.txt_email.setObjectName("txt_email")
        self.txt_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_password.setGeometry(QtCore.QRect(390, 360, 231, 31))
        self.txt_password.setStyleSheet("border: 2px solid #e67e22;\n"
"border-radius: 7px;\n"
"padding: 5px;")
        self.txt_password.setObjectName("txt_password")
        self.cf_pw = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.cf_pw.setGeometry(QtCore.QRect(390, 430, 231, 31))
        self.cf_pw.setStyleSheet("border: 2px solid #e67e22;\n"
"border-radius: 7px;\n"
"padding: 5px;")
        self.cf_pw.setObjectName("cf_pw")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 490, 83, 29))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(330, 540, 121, 20))
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 540, 83, 29))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Username"))
        self.label_2.setText(_translate("MainWindow", "Email"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.label_4.setText(_translate("MainWindow", "Confirm password"))
        self.pushButton.setText(_translate("MainWindow", "Create"))
        self.label_5.setText(_translate("MainWindow", "Have an account?"))
        self.pushButton_2.setText(_translate("MainWindow", "Log in"))
